services:
  - type: web
    name: ai-doctor-app
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y portaudio19-dev && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
