services:
  - type: web
    name: ai-doctor-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
